spring:
  application:
    name: kube-link
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:configs/db/db
  web:
    resources:
      static-locations: file:resource
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 15151
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
