name: build
run-name: build kube-link dist
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # install node
      - name: Install JDK and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with maven
        run: mvn clean package -e -U -B --file kube-link/pom.xml
      - name: Make distribution
        run: |
          mkdir -p kube-link-dist/configs/db kube-link-dist/resource
          mv kube-link/target/*.jar kube-link-dist/kube-link.jar
          mv kube-link/configs/db/* kube-link-dist/configs/db/
          # web page resource
          wget https://github.com/xiaoso456/kubelink-web/releases/download/v0.0.1-draft/dist.zip -P .
          unzip dist.zip -d kube-link-dist/resource

      - name: Package to zip
        run: |
          cd kube-link-dist
          zip -r kube-link-dist.zip .
          mv kube-link-dist.zip ../
      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "kube-link-dist.zip"
          prerelease: true
          name: kube-link
          tag: v0.0.1-draft
          body: "This is a draft release"




